//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Count { get; set; }
        public string Barcode { get; set; }
    }
}
